defaults: &defaults
  working_directory: ~/ReactiveDB
  docker:
    - image: circleci/node:14

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: echo 'export PATH=${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin' >> $BASH_ENV
      - run: curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
      - run: sudo ln -sf ~/.yarn/bin/yarn /usr/local/bin/yarn
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn-with-greenkeeper
          command: |
            sudo yarn global add greenkeeper-lockfile@1
            yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - run: greenkeeper-lockfile-update
      - run: npm run build_all
      - run: greenkeeper-lockfile-upload
      - persist_to_workspace:
          root: ~/ReactiveDB
          paths:
            - ./*
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ReactiveDB
      - run: npm run lint
      - run: npm run check_circular_dependencies
      - run: npm run cover
      - run: npm run test_O1
      - run:
          name: test-coverage
          command: npx codecov -f coverage/*.json

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ReactiveDB
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn publish_all

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              only: master
